#!/usr/bin/env python3
"""Generate lib/cc-session-registry.ts listing all baked sessions."""
import os, json
DATA = "app/data/sessions"
files = sorted([f for f in os.listdir(DATA) if f.endswith(".json")])
out = ["// AUTO-GENERATED by scripts/generate_session_registry.py — do not edit.",
       "// Run that script after baking new sessions.",
       "import type { CcSessionData } from './cc-sessions'",
       "",
       "export const SESSION_REGISTRY: Record<number, () => Promise<{ default: CcSessionData }>> = {"]
for fname in files:
    arrow_id = fname.replace(".json", "")
    out.append(f"  {arrow_id}: () => import('@/app/data/sessions/{fname}') as unknown as Promise<{{ default: CcSessionData }}>,")
out.append("}")
out.append("")
with open("lib/cc-session-registry.ts","w") as f:
    f.write("\n".join(out))
print(f"Wrote lib/cc-session-registry.ts with {len(files)} entries: {[f.replace('.json','') for f in files]}")
